version: "3.9"
services:
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
volumes:
  db_data: